/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnBoardingRouteImport } from './routes/onBoarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemeEditorThemeIdRouteImport } from './routes/theme-editor.$themeId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnBoardingRoute = OnBoardingRouteImport.update({
  id: '/onBoarding',
  path: '/onBoarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeEditorThemeIdRoute = ThemeEditorThemeIdRouteImport.update({
  id: '/theme-editor/$themeId',
  path: '/theme-editor/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/onBoarding': typeof OnBoardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/theme-editor/$themeId': typeof ThemeEditorThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/onBoarding': typeof OnBoardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/theme-editor/$themeId': typeof ThemeEditorThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/onBoarding': typeof OnBoardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/theme-editor/$themeId': typeof ThemeEditorThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/faq'
    | '/login'
    | '/onBoarding'
    | '/pricing'
    | '/settings'
    | '/theme-editor/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/faq'
    | '/login'
    | '/onBoarding'
    | '/pricing'
    | '/settings'
    | '/theme-editor/$themeId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/faq'
    | '/login'
    | '/onBoarding'
    | '/pricing'
    | '/settings'
    | '/theme-editor/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OnBoardingRoute: typeof OnBoardingRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  ThemeEditorThemeIdRoute: typeof ThemeEditorThemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onBoarding': {
      id: '/onBoarding'
      path: '/onBoarding'
      fullPath: '/onBoarding'
      preLoaderRoute: typeof OnBoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-editor/$themeId': {
      id: '/theme-editor/$themeId'
      path: '/theme-editor/$themeId'
      fullPath: '/theme-editor/$themeId'
      preLoaderRoute: typeof ThemeEditorThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OnBoardingRoute: OnBoardingRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  ThemeEditorThemeIdRoute: ThemeEditorThemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
