/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoSettingsRouteImport } from './routes/demo/settings'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOnBoardingRouteImport } from './routes/_app/onBoarding'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as DemoThemeEditorThemeIdRouteImport } from './routes/demo/theme-editor.$themeId'
import { Route as AppThemeEditorThemeIdRouteImport } from './routes/_app/theme-editor.$themeId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnBoardingRoute = AppOnBoardingRouteImport.update({
  id: '/onBoarding',
  path: '/onBoarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoThemeEditorThemeIdRoute = DemoThemeEditorThemeIdRouteImport.update({
  id: '/theme-editor/$themeId',
  path: '/theme-editor/$themeId',
  getParentRoute: () => DemoRouteRoute,
} as any)
const AppThemeEditorThemeIdRoute = AppThemeEditorThemeIdRouteImport.update({
  id: '/theme-editor/$themeId',
  path: '/theme-editor/$themeId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AppAppRoute
  '/onBoarding': typeof AppOnBoardingRoute
  '/settings': typeof AppSettingsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
  '/theme-editor/$themeId': typeof AppThemeEditorThemeIdRoute
  '/demo/theme-editor/$themeId': typeof DemoThemeEditorThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AppAppRoute
  '/onBoarding': typeof AppOnBoardingRoute
  '/settings': typeof AppSettingsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo': typeof DemoIndexRoute
  '/theme-editor/$themeId': typeof AppThemeEditorThemeIdRoute
  '/demo/theme-editor/$themeId': typeof DemoThemeEditorThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_app/app': typeof AppAppRoute
  '/_app/onBoarding': typeof AppOnBoardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
  '/_app/theme-editor/$themeId': typeof AppThemeEditorThemeIdRoute
  '/demo/theme-editor/$themeId': typeof DemoThemeEditorThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/app'
    | '/onBoarding'
    | '/settings'
    | '/demo/settings'
    | '/demo/'
    | '/theme-editor/$themeId'
    | '/demo/theme-editor/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/app'
    | '/onBoarding'
    | '/settings'
    | '/demo/settings'
    | '/demo'
    | '/theme-editor/$themeId'
    | '/demo/theme-editor/$themeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/_app/app'
    | '/_app/onBoarding'
    | '/_app/settings'
    | '/demo/settings'
    | '/demo/'
    | '/_app/theme-editor/$themeId'
    | '/demo/theme-editor/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onBoarding': {
      id: '/_app/onBoarding'
      path: '/onBoarding'
      fullPath: '/onBoarding'
      preLoaderRoute: typeof AppOnBoardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/demo/theme-editor/$themeId': {
      id: '/demo/theme-editor/$themeId'
      path: '/theme-editor/$themeId'
      fullPath: '/demo/theme-editor/$themeId'
      preLoaderRoute: typeof DemoThemeEditorThemeIdRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_app/theme-editor/$themeId': {
      id: '/_app/theme-editor/$themeId'
      path: '/theme-editor/$themeId'
      fullPath: '/theme-editor/$themeId'
      preLoaderRoute: typeof AppThemeEditorThemeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppOnBoardingRoute: typeof AppOnBoardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThemeEditorThemeIdRoute: typeof AppThemeEditorThemeIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppOnBoardingRoute: AppOnBoardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThemeEditorThemeIdRoute: AppThemeEditorThemeIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoThemeEditorThemeIdRoute: typeof DemoThemeEditorThemeIdRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoSettingsRoute: DemoSettingsRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoThemeEditorThemeIdRoute: DemoThemeEditorThemeIdRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
